### ISSUE TITLE
Create /mnt/ec2-root/

### ISSUE THREAD

**Issue by rdrgmnzs** [ferricoxide/AMIgen#20]
Check if /mnt/ec2-root/ exists if not create it.

**Comment by ferricoxide** [comment]
d'oh! Meant to do that. Thanks for the reminder.

**Comment by rdrgmnzs** [comment]
Thanks for the scripts and all the work you put into them. Cheers!

**Comment by ferricoxide** [comment]
I might move the create-dir logic into an external module callable from the other scripts, but, for now, I added it to the `MkChrootTree.sh` script.

My laptop's harddisk controller crapped out, this weekend (gotta see if I can rush-order a replacement!), so I'm running blind at the moment. I've not committed to the master branch just in case there's bugs in the logic. Can you pull the 'FixMissingRoot' branch and let me know if the check-block properly handles a missing ${CHROOT}? If it's good, I'll merge it in.

**Comment by rdrgmnzs** [comment]
Just finished testing the check-block it works like a charm!

Damn Sorry about the laptop!

**Comment by rdrgmnzs** [comment]
Just as a note I copied the check-block onto the master branch before testing as it looks like the  'FixMissingRoot' is derived from an old branch.

**Comment by ferricoxide** [comment]
The down side of trying to pop a quick-fix from my backup laptop.

Any way, I'll stash the fix, discard the branch and push the stash into the master, shortly.

**Comment by rdrgmnzs** [comment]
Awesome thanks!

**Comment by ferricoxide** [comment]
Pushed.
