### ISSUE TITLE
CHROOT not set in MkCfgFiles.sh 

### ISSUE THREAD

**Issue by rdrgmnzs** [ferricoxide/AMIgen#21]
[root@test AMIgen]# ./MkCfgFiles.sh 
chroot: cannot change root directory to rpm: No such file or directory
deleted /mnt/ec2-root/etc/grub.conf
deleted /mnt/ec2-root/boot/grub/menu.lst

**Comment by ferricoxide** [comment]
Silly question: did you hit the above in the branch or in the master? I think that when I did the quick-branch on my backup laptop, I may have had a stale local repo that I branched from (the yum*.conf files were stale when I just tried to start duplicating the issue).

**Comment by rdrgmnzs** [comment]
I hit this while running the script from the master branch. From what I've been able to gather the first if-block is using ${CHROOT} when it is not set and so chroot tries to use the 'rpm' command as a location. I believe you intend to use ${ALTROOT} instead of ${CHROOT} if I understand what is going on there correctly.

**Comment by ferricoxide** [comment]
Ah. Yeah. I changed the mid-stream. My workaround had been "set CHROOT in the build-env" (along with YUM0 if you don't want to have to patch the build-bootstrap instance before running the chroot-build).

I'd _thought_ that I'd put the requisite graceful-fail in place if people _didn't_ set CHROOT, but looks like I missed something.

**Comment by rdrgmnzs** [comment]
Sweet Thanks!
