### ISSUE TITLE
CentOS 7 issues / Question

### ISSUE THREAD

**Issue by rdrgmnzs** [ferricoxide/AMIgen#22]
Are the scripts supposed to handle CentOS 7 as well or are they only designed for 6? I'm seeing various issues relating to sed when trying to build a CentOS 7 box.

This is more of a question than anything else, I can create issues for the specific errors I'm seeing just wanted to know if it is something the scripts were intended for before I do so.

**Comment by ferricoxide** [comment]
Hadn't specifically tested on CentOS 7. That said, one of the `sed` errors will happen if "/tmp" isn't mounted as a pseudodevice (the AMIs expect /tmp to allocate from swap as a "tmpfs"). This design decision was based on the fact that most of the installs I support have A/V installed and A/V _kills_ performance if /tmp isn't a memory-based filesystem. Plus, my background before Linux was commercial UNIX variants, and all of the ones I'd worked with (this century) had /tmp as tmpfs.

**Comment by rdrgmnzs** [comment]
Got it I actually ran into the /tmp error when building CentOS6 and quickly realized my mistake after looking at the docs. But the errors I'm getting when building CentOS 7 are different and I've double checked to make sure that /tmp is allocated from swap.

Thanks for the reply I'll take a look and see what details I can find, and will either open specific tickets for them or do a pr if I can.

**Comment by ferricoxide** [comment]
Yeah. I probably need to more-gracefully handle the `/tmp`. In the environments I work in, `/tmp` as its own (tmpfs-based) filesystem is kind of a given.

**Comment by ferricoxide** [comment]
@brdude 

Just thought I'd update you, in case you hadn't found a solution, yet.

With the EL7 draft STIG's being published in January, I finally had impetus to work on this. I'm still part-way through, but i started the [AMIgen7](ferricoxide/AMIgen7) project (which is also why this project was renamed to AMIgen6). Right now, [AMIgen7](ferricoxide/AMIgen7) is only useful for creating a two-partition — boot&root — CentOS 7 AMI. However, I've been trying to structure it so it will work whether you want STIG-LVM or just boot&root.

**Comment by rdrgmnzs** [comment]
@ferricoxide thanks for the heads up! I actually moved to using packer by hashicorp to create a template using VirtualBox and then upload that to AWS as a base structure for my AMIs. 

And a second packer run on that AMI would create a template ready for usage with all the updates and anything else I needed in it.

**Comment by ferricoxide** [comment]
Cool. Has Amazon improved import times? Last time I'd used VM-based import methods, it caused me to to switch to the chroot-method. Even with a 50Mbps link, the imports were taking longer than I was willing to sit for (and longer than the chroot-build method was taking).

Also: have you noticed whether EL7 is PV-compatible? When I take my images and try to use them with PV, the PV chain-loader seems to balk when moving from PV-GRUB to GRUB2. Curious, I'd looked at both the Red Hat 7 and CentOS 7 MarketPlace offerings and found only HVM AMIs - no PV AMIs.

**Comment by rdrgmnzs** [comment]
It takes about 20min for an upload on a 2GB image to upload and become ready if I remember correctly. It's a bit painful to wait for but since I'm just using it to create a base and only do some on rare occasions it's something I can put up with.

**Comment by ferricoxide** [comment]
Cool. So, about the same speed it was running at previously.

I'll probably have to give it another look when one of the customers I work for opts to go multi-cloud.
