### ISSUE TITLE
MkCfgFiles.sh: Duplicates functionality of MkTabs.sh

### ISSUE THREAD

**Issue by lorengordon** [ferricoxide/AMIgen#34]
[These lines](https://github.com/ferricoxide/AMIgen6/blob/master/MkCfgFiles.sh#L38-L66) are handled by MkTabs.sh. Not sure why they are duplicated in MkCfgFiles.sh? Might be related to why [README.scripts](https://github.com/ferricoxide/AMIgen6/blob/master/README.scripts#L46) says to run MkTabs.sh twice?

**Comment by ferricoxide** [comment]
Scripts were written on the fly - some larger scripts were broken out into stand alones (and the remaining parent script renamed). May have missed a cleanout on a parent script.
