### ISSUE TITLE
PreLabel.sh: logger: unknown priority name: local0

### ISSUE THREAD

**Issue by lorengordon** [ferricoxide/AMIgen#35]
If selinux happens to be disabled, the `fatal` [function](https://github.com/ferricoxide/AMIgen6/blob/master/PreRelabel.sh#L12-L16) attempts to log to the priority `-p local0`, but local0 is not recognized.

```
$ sudo /tmp/el-build/PreRelabel.sh
SELinux not enabled on build-host
logger: unknown priority name: local0.
```

**Comment by ferricoxide** [comment]
Oops... Set the facility but not the level. Fixing...
