### ISSUE TITLE
CleanChroot.sh: Double entry for `distro: rhel`

### ISSUE THREAD

**Issue by lorengordon** [ferricoxide/AMIgen#51]
```
$ sudo /tmp/el-build/CleanChroot.sh
Loaded plugins: amazon-id, product-id, rhui-lb, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Cleaning repos: epel rhui-REGION-client-config-server-6 rhui-REGION-rhel-server-releases rhui-REGION-rhel-server-rh-common
0 package files removed
Setting default cloud-init user to maintuser
$ cat $CHROOT/etc/cloud/cloud.cfg
# ... elided ...
system_info:
  default_user:
    name: maintuser
    lock_passwd: true
    gegos: Maintenance User
    groups: [wheel, adm]
    sudo: ["ALL=(root) NOPASSWD:ALL"]
    shell: /bin/bash
  distro: rhel
  distro: rhel
```

**Comment by lorengordon** [comment]
Also, isn't `gegos` supposed to be `gecos`?

**Comment by ferricoxide** [comment]
Fmeh. Typo. That will make the default-user account not accessible.

-tom

**Comment by ferricoxide** [comment]
Ok. When I run the script, I'm only seeing one incidence of `distro: rhel` in the resulting output. Given how the script works, I'm not sure how a redundant line would get in there. Have to spin up an RHEL instance to see if it's starting `cloud.cfg` file is formatted differently from the CentOS one. :-\

**Comment by lorengordon** [comment]
Yep, it's only on RHEL...

**Comment by ferricoxide** [comment]
RHEL formats their file differently. Puts the `distro` line immediately after `system_info:` rather than after the `default_user` stanza.

Bandaids on top of bandaids... It's like the fix for plus3it/join-domain-formula/issues/45 will be (since, the reason _that_ issue occurs is because of a bandaid for bad AD config).
