### ISSUE TITLE
MkChrootTree.sh doesn't verify that $CHOOT/selinux exists before attempting bind-mount

### ISSUE THREAD

**Issue by ferricoxide** [ferricoxide/AMIgen#59]
Add logic to ensure that `${CHROOT}/selinux` exists prior to mount attempt.

**Comment by lorengordon** [comment]
I thought I fixed that already?

https://github.com/ferricoxide/AMIgen6/issues/48
https://github.com/ferricoxide/AMIgen6/pull/52

**Comment by ferricoxide** [comment]
Dunno. The mkdir that was already in the script /should/ have worked.
Unfortunately, at least with the one running of the code, it popped an
error the the bind-mount. It's part of why I put the "shouldn't need to
do this" comment before the `if -d` section.
