### ISSUE TITLE
Need Better Handling of EPEL in AWScliSetup.sh

### ISSUE THREAD

**Issue by ferricoxide** [ferricoxide/AMIgen#61]
Current method creates "weirdness" when deployed in the context of a private network. Need to ensure that the value for the EPEL package can be forced to null.

**Comment by lorengordon** [comment]
The idea was to have a 'private' EPEL rpm that we could pass in, in place of the url to the public rpm...

**Comment by ferricoxide** [comment]
Two problems with current method:

  * It defaults to the public URL if no value is passed: this causes
    errors when moved to a private network.
  * If the private network's yum repos contains an epel-release RPM (as
    is the case with full/dumb-sync repo-copies) /and /that RPM hasn't
    been localized, the public EPEL defs get installed ...which causes
    failures when the system can't resolve the (public) URLs: you get
    messages about not being able to resolve epel.

**Comment by ferricoxide** [comment]
Two problems with current method:
- It defaults to the public URL if no value is passed: this causes errors when moved to a private network.
- If the private network's yum repos contains an epel-release RPM (as is the case with full/dumb-sync repo-copies) _and_ that RPM hasn't been localized, the public EPEL defs get installed ...which, in turn, causes failures when the system can't resolve the (public) URLs. This causes messages about not being able to resolve epel.

**Comment by ferricoxide** [comment]
While testing updates to `ChrootBuild.sh`, ran the `AWScliSetup.sh` with ARG2 set to private EPEL repo. Functioned as desired. May still have sharp-edges I haven't encountered, though.
